import React from 'react';
import { Lead, Property } from '../types';
import { CalendarDays, CheckCircle2, Clock3, Heart, MessageSquare } from 'lucide-react';

interface ClientAccountProps { savedProperties: Property[]; leads: Lead[]; onOpenDetails: (property: Property) => void; }

export const ClientAccount: React.FC<ClientAccountProps> = ({ savedProperties, leads, onOpenDetails }) => (
  <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-10 py-8 space-y-6">
    <header className="border-b border-white/10 pb-6"><span className="text-[10px] uppercase tracking-[0.35em] text-red-400 font-black">Client account // your search</span><h1 className="font-headline text-3xl sm:text-5xl font-black italic uppercase text-white mt-2">Keep your next home moving.</h1><p className="text-sm text-zinc-400 max-w-2xl mt-3">Your saved homes, viewing requests, and conversations stay together so you can make a confident decision.</p></header>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><AccountMetric label="Saved properties" value={savedProperties.length} icon={<Heart className="w-4 h-4" />} /><AccountMetric label="Open enquiries" value={leads.filter((lead) => lead.status !== 'Closed').length} icon={<MessageSquare className="w-4 h-4" />} accent="text-red-400" /><AccountMetric label="Scheduled viewings" value={leads.filter((lead) => lead.status === 'Tour_Scheduled').length} icon={<CalendarDays className="w-4 h-4" />} accent="text-emerald-400" /></div>
    <section><div className="flex items-center justify-between border-b border-white/10 pb-3"><h2 className="font-headline text-2xl font-black italic uppercase text-white">Saved properties</h2><span className="text-[10px] uppercase tracking-wider text-zinc-500">Private to you</span></div>{savedProperties.length === 0 ? <div className="border border-dashed border-white/15 p-10 text-center mt-4"><Heart className="w-8 h-8 text-zinc-600 mx-auto mb-3" /><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">No saved properties yet</p></div> : <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">{savedProperties.map((property) => <button key={property.id} onClick={() => onOpenDetails(property)} className="text-left border border-white/10 bg-black/60 p-3 flex gap-4 hover:border-red-500/50"><img src={property.thumbnail_url} alt={property.title} className="w-28 h-24 object-cover" /><span className="min-w-0"><strong className="block text-sm uppercase text-white truncate">{property.title}</strong><span className="block text-xs text-zinc-500 mt-1">{property.location.city} • {property.property_type === 'Live' ? 'For home' : 'For investment'}</span><span className="block font-mono text-sm text-white mt-3">${property.price.toLocaleString()}</span></span></button>)}</div>}</section>
    <section><div className="flex items-center justify-between border-b border-white/10 pb-3"><h2 className="font-headline text-2xl font-black italic uppercase text-white">Your activity</h2><span className="text-[10px] uppercase tracking-wider text-zinc-500">Requests and viewings</span></div><div className="divide-y divide-white/10">{leads.map((lead) => <div key={lead.id} className="py-4 flex items-center gap-4"><div className="w-9 h-9 border border-white/10 bg-black flex items-center justify-center"><StatusIcon status={lead.status} /></div><div className="min-w-0 flex-1"><strong className="block text-sm text-white">{lead.property_title || 'General enquiry'}</strong><span className="text-xs text-zinc-500">{lead.intent} • {lead.inquiry_type.replace('_', ' ')} • {lead.status.replace('_', ' ')}</span></div><Clock3 className="w-4 h-4 text-zinc-600" /></div>)}</div></section>
  </div>
);

const AccountMetric: React.FC<{ label: string; value: number; icon: React.ReactNode; accent?: string }> = ({ label, value, icon, accent = 'text-white' }) => <div className="border border-white/10 bg-black/60 p-4"><div className={`flex items-center justify-between text-[9px] uppercase tracking-[0.2em] font-black ${accent}`}><span>{label}</span>{icon}</div><strong className={`block text-3xl font-mono mt-2 ${accent}`}>{value}</strong></div>;
const StatusIcon: React.FC<{ status: Lead['status'] }> = ({ status }) => status === 'Closed' ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : status === 'Tour_Scheduled' ? <CalendarDays className="w-4 h-4 text-blue-400" /> : <MessageSquare className="w-4 h-4 text-red-400" />;